module Extraction

using ..Types
using ..Topology
using LinearAlgebra
using DataStructures

export QuadMesh, extract_quad_mesh

# --- 1. Data Structure ---
struct QuadMesh
    vertices::Vector{Point3D}
    quads::Vector{Tuple{Int,Int,Int,Int}} # Indices into vertices (1-based)
end

# --- 2. Grid Sampling Logic ---

"""
    extract_quad_mesh(topo, u, v; h_scale=1.0)

Generates a QuadMesh by sampling the integer grid of the (u,v) parameterization.
Note: This produces a 'chart-based' mesh. Seams might be geometrically aligned 
but not topologically welded if there are rotation jumps. This is perfect for visualization.
"""
function extract_quad_mesh(topo::MeshTopology, u::Vector{Float64}, v::Vector{Float64})
    println("\n--- Extracting Quad Mesh (Integer Grid Sampling) ---")
    
    # Store unique 3D points found at integer coordinates (u_int, v_int)
    # We use a Dict to merge vertices that land on the same integer coord
    # Key: (round(u), round(v)) -> Vertex Index
    node_map = Dict{Tuple{Int,Int}, Int}()
    
    quad_verts = Point3D[]
    quad_faces = Tuple{Int,Int,Int,Int}[]
    
    # Helper to get/create vertex index
    function get_node_idx(ui, vi, p3d)
        key = (ui, vi)
        if haskey(node_map, key)
            return node_map[key]
        else
            push!(quad_verts, p3d)
            idx = length(quad_verts)
            node_map[key] = idx
            return idx
        end
    end

    # Iterate over all mesh triangles
    # We treat the parameterization as a set of linear maps per triangle.
    for (f_idx, tri) in enumerate(topo.faces)
        # 1. Get UV bounding box for this triangle
        us = [u[tri[1]], u[tri[2]], u[tri[3]]]
        vs = [v[tri[1]], v[tri[2]], v[tri[3]]]
        
        min_u, max_u = floor(Int, minimum(us)), ceil(Int, maximum(us))
        min_v, max_v = floor(Int, minimum(vs)), ceil(Int, maximum(vs))
        
        # 2. Iterate all integer candidates in the box
        for i in min_u:max_u
            for j in min_v:max_v
                
                # We want to check if the quad (i,j) -> (i+1, j+1) is inside this triangle.
                # Actually, simpler: We check if specific POINTS are inside, then form quads later?
                # BETTER: For visualization, we iterate the integer GRID CELLS. 
                # If a grid cell is mostly inside the triangle, we generate it.
                # BUT: A grid cell usually spans multiple triangles.
                
                # ROBUST STRATEGY: 
                # Sample the integer points. If we find (i,j), (i+1,j), (i+1,j+1), (i,j+1)
                # all generated by the SAMETHING (or neighbors), we build a quad.
                
                # Let's stick to the "Inverse Map" method:
                # For a point (i, j), is it inside triangle T?
                
                # Barycentric coords for P(i,j)
                p_uv = [Float64(i), Float64(j)]
                
                # Triangle UVs
                uv1 = [us[1], vs[1]]
                uv2 = [us[2], vs[2]]
                uv3 = [us[3], vs[3]]
                
                # Solve: p_uv = w1*uv1 + w2*uv2 + w3*uv3
                #        w1 + w2 + w3 = 1
                # This is a 2x2 linear system (after eliminating w3)
                
                v0 = uv2 - uv1
                v1 = uv3 - uv1
                v2 = p_uv - uv1
                
                denom = v0[1]*v1[2] - v1[1]*v0[2]
                if abs(denom) < 1e-10; continue; end
                
                w2 = (v2[1]*v1[2] - v1[1]*v2[2]) / denom
                w3 = (v0[1]*v2[2] - v2[1]*v0[2]) / denom
                w1 = 1.0 - w2 - w3
                
                # Check if inside triangle (with slight epsilon to catch edges)
                eps = -1e-4
                if w1 >= eps && w2 >= eps && w3 >= eps
                    # Point is valid! Map to 3D.
                    p1 = topo.vertices[tri[1]]
                    p2 = topo.vertices[tri[2]]
                    p3 = topo.vertices[tri[3]]
                    
                    x = w1*p1.x + w2*p2.x + w3*p3.x
                    y = w1*p1.y + w2*p2.y + w3*p3.y
                    z = w1*p1.z + w2*p2.z + w3*p3.z
                    
                    # Register this point
                    # We store it associated with THIS chart (triangle group?)
                    # To allow simple merging, we assume the solver aligned jumps to integers.
                    # So (i,j) in one face should match (i,j) in neighbor.
                    get_node_idx(i, j, Point3D(x, y, z))
                end
            end
        end
    end
    
    # 3. Generate Topology
    # Connect existing nodes (i,j) -> (i+1, j) etc.
    # We simply iterate the populated map.
    sorted_keys = collect(keys(node_map))
    
    # We use a set to avoid duplicates (e.g. if we iterate cells)
    quad_set = Set{Tuple{Int,Int,Int,Int}}()
    
    for (key, idx_bl) in node_map
        i, j = key
        
        # Check for neighbors
        if haskey(node_map, (i+1, j)) && 
           haskey(node_map, (i+1, j+1)) && 
           haskey(node_map, (i, j+1))
           
           idx_br = node_map[(i+1, j)]
           idx_tr = node_map[(i+1, j+1)]
           idx_tl = node_map[(i, j+1)]
           
           # Form Quad (CCW)
           q = (idx_bl, idx_br, idx_tr, idx_tl)
           push!(quad_faces, q)
        end
    end
    
    println("  Extracted $(length(quad_verts)) vertices and $(length(quad_faces)) quads.")
    return QuadMesh(quad_verts, quad_faces)
end

end